### PR TITLE
unsubscribe on destroy

### PR DESCRIPTION
**Pull request by bomberest**

### CODE REVIEW

**Review by JochenHeckl — COMMENTED** [review]
First of all thanks for the contribution!

When looking at the code however I would prefer a solution like this:
```
public void void OnDestroy()
{
    if( DataSource != null )
    {
        DataSource = null;
    }
}
```
to make sure the DataSource gets fully disconnected.

In my use cases data sources do not outlive views. However I could imaging scenarios where this could be useful.

Would you mind explaining your use case where you ran into problems.

**Comment by bomberest** [comment]
Hello! I have meta gameplay HexItem models that i use for data biding and they have long lifetime and i using them in many destroyable windows

image

image

**Comment by bomberest** [comment]
DataSource has getter with get component in parent that a little redundant

**Comment by JochenHeckl** [comment]
I commited the solution

if( DataSource != null )
{
    DataSource = null;
}

on main.

Please feel free to follow up if you would prefer a better alternative.

**Pull request closed without merging**
